### ISSUE TITLE
Error: failed to connect to [81:27017]

### ISSUE THREAD

**Issue by berzas** [RocketChat/Rocket.Chat.RaspberryPi#15]
Hi,

When I run whit my user and password:

`PORT=3000 ROOT_URL=http://localhost:3000   MONGO_URL=mongodb://<user>:<password>@<host>:<port>/dataurlfrommongolabs    $HOME/meteor/dev_bundle/bin/node main.js`

I get:

Error: failed to connect to [81:27017]

I created a db on https://mlab.com
What shoul I do?

Thanks

**Comment by Sing-Li** [comment]
Come join the community at https://demo.rocket.chat/channel/raspberrypi

And someone can help in real-time :)
