### ISSUE TITLE
Audio/Video not working

### ISSUE THREAD

**Issue by abiank** [RocketChat/Rocket.Chat.RaspberryPi#17]
I installed according to the guide and everything starts but clicking on the microphone icon does nothing, any ideas? Tried both Chrome and FF.

**Comment by Sing-Li** [comment]
@sblank

So you will need:

1) HTTPS => either ngrok or an nginx / apache with its own CERT
2) the latest binaries via the `curl` command

for it to work.  I'd suggest you try with your friends/colleagues on our server first - to understand how it works:

https://demo.rocket.chat
