### ISSUE TITLE
Improvemnt for documentation to install meteor universal

### ISSUE THREAD

**Issue by TomFreudenberg** [RocketChat/Rocket.Chat.RaspberryPi#18]
Hi @Sing-Li 

Cool repo here 👍 I like it!

Just to inform you: Meteor universal ist now on release 1.3.3.1.

So if you run `git clone` without a branch it will head always to the latest marked branch when we switch that on github. If you want to point to a special meteor release, you may add the branch to be stable for deployment.

```
git clone --depth 1 -b release-1.3.3.1-universal https://github.com/4commerce-technologies-AG/meteor.git meteor
```

Cheers
Tom

**Comment by Sing-Li** [comment]
@TomFreudenberg    Thanks, Tom!     Congrats on Meteor universal releasing on 1.3.3.1  !  Stellar ! 

I'll update the instructions to pull the 1.2.1 branch, and inform the community.  Thanks for the heads-up.

One question :  Does this mean it supports the ARM v8 binaries native, or not quite yet?  (a few of us now have Pine A64 now facing the hardware-ahead-of-software phenomenon)

**Comment by TomFreudenberg** [comment]
Hi @Sing-Li 

unfortunately current meteor stable still delivers node v0.10.x (45) branch. That is not possible to run on the v8 (64bit) architecture. But there are good news ;-) Next meteor release 1.4 will come up with node 4.x and mongo 3.2. I guess this is a kind of possible sources. We will give it a try soon.

Would be nice if you watch the universal repo for any changes about that.

Cheers
Tom

**Comment by Sing-Li** [comment]
@TomFreudenberg 

> Would be nice if you watch the universal repo for any changes about that.

Absolutely!  Thanks for the tip!  👌

**Comment by Sing-Li** [comment]
@TomFreudenberg   Is there a branch of Meteor universal that is at par with the 1.4.1  Meteor release?   We've migrated 0.40.0 to 1.4.1 and would like to build the ARM binaries if possible.
