### ISSUE TITLE
problems with mobile clients

### ISSUE THREAD

**Issue by defcon1702** [RocketChat/Rocket.Chat.RaspberryPi#19]
If I try to connect to my raspberry pie version of rocket.chat the interface dont work. Only html text interface without a gui around it. Any ideas?

**Comment by spfbnmgkitr-1764** [comment]
Same issue. Web and mobile web were perfect, but iOS client was html only.

**Comment by Sing-Li** [comment]
@defcon1702 and @spfbnmgkitr-1764  - do you still have the problem?

Make sure your ROOT_URL is exactly the same as how you're addressing the server.  And reboot the sever after ROOT_URL is updated.

**Comment by spfbnmgkitr-1764** [comment]
I'm sorry @Sing-Li but I don't understand.  My ROOT_URL is set to http://localhost:3000 in the startup script, but that's not what I type in the address bar to access it.  Is there anyway that you could get a little more specific?

**Comment by spfbnmgkitr-1764** [comment]
I'm sorry @Sing-Li but I still don't understand.  I replaced http://localhost:3000 with https://chat.sample.com as the ROOT_URL in the startup script and I'm still having the same issue when I try to connect with the iOS app after rebooting the server.
