### ISSUE TITLE
Mobile iOS notifications not working fully

### ISSUE THREAD

**Issue by JoeArcher007** [RocketChat/Rocket.Chat.RaspberryPi#21]
`iOS V. 9.3.4 (13G35)
iPhone 6s
Rocket.Chat App`

I have a couple rooms enabled that have all messages set to notify. Unfortunately, it doesn't' appear that they are being sent when a message arrives. 

I'm using the application Franz (http://meetfranz.com/) that is connected also to the Rocketchat server I have created. It receives desktop notifications fine.

As well, when I run the "test mobile notification" it sends out correctly and I see the test.

Mentions are working OK as well I believe, but I'll have to test again.

Rocket.Chat Server Info
Version: 0.34.0

Please let me know if there is any other information needed.

**Comment by JoeArcher007** [comment]
Tested with mentions, and they work correctly. 

Can't seem to see exactly what is happening to cause it.

**Comment by FAD0** [comment]
RocketChat isn't usable on iPhone.  RocketChat+ seems better, but it doesn't work with v0.39.0.  It requires v0.54 or higher.  Is it possible to get an updated version so it can be used with Rocketchat+?

**Comment by Sing-Li** [comment]
The latest "experimental" apps should have this working.   See your personal profile to set your own notification preference.   

Please re-open if problem persists.   Also best to follow up on Rocket.Chat repository as this is not a Raspberry Pi specific problem.
