### ISSUE TITLE
ngrok instructions

### ISSUE THREAD

**Issue by brevvis** [RocketChat/Rocket.Chat.RaspberryPi#26]
Hi, the instructions for installing ngrok asks the user to run the following command:

`curl https://dl.ngrok.com/ngrok_2.0.19_linux_arm.zip -o ngrok.zip unzip ngrok.zip cd ngrok ./ngrok http 3000`

However, on a newly installed Ubtuntu Core server, doing so gives this result:

`-bash: curl: command not found`

How do you actually get Ngrok on the Pi?

**Comment by brevvis** [comment]
If ngrok can't be installed because there's no ngrok snap, is there a different way to solve this?

**Comment by mcmarto** [comment]
`sudo apt-get install curl`

**Comment by Sing-Li** [comment]
Please see updated instructions.  Snap is now solidly supported on Raspbian Buster (and later) and you can readily install ngrok.   No need to use Ubuntu Core any more.
