### ISSUE TITLE
Raspberry pi zero intructions 

### ISSUE THREAD

**Issue by Darkcast** [RocketChat/Rocket.Chat.RaspberryPi#27]
The raspberry pi zero instructions are incorrect the link are dead and if can find the correct version it breaks and it never installs

**Comment by kunguz** [comment]
I am also effected from the same situation, snap installation ends with an illegal instruction warning.

**Comment by Sing-Li** [comment]
Unfortunately, the size of Rocket.Chat server core has grown beyond what the Raspberry Pi zero can support - even with the most severe hacks. 

Please use snap based install on Raspberry Pi 4 or better for the smoothest setup experience.
