### ISSUE TITLE
Snap "core" core-support-plug

### ISSUE THREAD

**Issue by letohicy** [RocketChat/Rocket.Chat.RaspberryPi#28]
Good day everyone,

I'm currently trying to test Rocket.chat on my RPI 3, before deploying it on an other server for a group. Unfortunetly, I'm blocked during the install, and don't understand why. (I'm like a beginner in linux and Raspberry)

For now, I've install ca-certificates `sudo apt install snapd ca-certificates`
But when I lunch the install for rocketchat with `sudo snap install rocketchat-server` it run without end on `2017-08-26T14:01:11+02:00 INFO snap "core" has bad plugs or slots: core-support-plug (unknown interface)
error: cannot perform the following tasks:
- Run configure hook of "core" snap if present (run hook "configure"`

When I stop it after few hours, I have `ERROR: ld.so: object '/usr/lib/arm-linux-gnueabihf/libarmmem.so' from /etc/ld.so.preload cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object '/usr/lib/arm-linux-gnueabihf/libarmmem.so' from /etc/ld.so.preload cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object '/usr/lib/arm-linux-gnueabihf/libarmmem.so' from /etc/ld.so.preload cannot be preloaded (cannot open shared object file): ignored.`

I don't understand the problem with "core".
Anybody could give me a hand on this problem?

Thank you for your help by advence, and sorry for my english :)

**Comment by Sing-Li** [comment]
This is a binary upstream (dnsutil) problem that has plagued many for a period of time.

Using that latest (July 2019) Raspbian Buster with the latest snap release should eliminate this (now corrected upstream) problem.
