### ISSUE TITLE
`GLIBC_2.15' not found (required by /home/pi/meteor/dev_bundle/bin/node)

### ISSUE THREAD

**Issue by dmkanter** [RocketChat/Rocket.Chat.RaspberryPi#3]
when i try to install rocket.chat on my raspberrypi 2, i get the following error

`pi@retropie ~/rocketchat/bundle/programs/server $ ~/meteor/dev_bundle/bin/npm install`
`GLIBC_2.15' not found (required by /home/pi/meteor/dev_bundle/bin/node)`

**Comment by RocketChatApp** [comment]
Hi David,

Please visit https://demo.rocket.chat/ ,  and come into the #raspberrypi
 channel.

We'll help get your Rocket.Chat server running on your Pi    :-)

Thanks.

 - Sing

**Comment by dmkanter** [comment]
was using wheezy instead of jessie. it's installing now, thanks!
