### ISSUE TITLE
Rocket.chat throws exception after updating to 0.62.1

### ISSUE THREAD

**Issue by frederiktoft** [RocketChat/Rocket.Chat.RaspberryPi#31]
I have written about this over at open.rocket.chat and forums.rocket.chat but might as well post it here since I saw one other having the same problem, and there has been zero communication from rocket.chat devs.

I have a rpi3 running ubuntu core and rocket.chat installed as a snap. Regular standard install, nothing custom, just have caddy enabled.
About three weeks ago, it updated automatically to version 0.62.1, but since then I have been unable to access the site. It just says “502 bad gateway”. After digging around this is the error that I found after using this command “sudo journalctl -u snap.rocketchat-server.rocketchat-server”:
![image](https://user-images.githubusercontent.com/1586864/38918085-f35a1c86-42ec-11e8-88f7-5efdc525cfac.png)
About a week after noticing this issue I got some clarification over on open.rocket.chat from “sing.li” regarding the exception. According to him it seems that the module “sharp” is trying to load a non ARM binary, resulting in the error.
I have also tried to just uninstall and reinstall rocket.chat, just starting over and still the same error, and I tried to roll back before that, still same error. I don't understand why a breaking bug like this is allowed to persist for so long.

**Comment by Sing-Li** [comment]
Please try the latest 1.0.x official snap based release.   And re-open if problem still exists.
