### ISSUE TITLE
Rocket.Chat on Pi 3b fibers/future.js:278 throws error

### ISSUE THREAD

**Issue by eszeus** [RocketChat/Rocket.Chat.RaspberryPi#32]
Hello,

Installed rocketchat on a new Pi 3b Setup, used the manual installation guide
https://github.com/RocketChat/Rocket.Chat.RaspberryPi

Now it gives me some error when starting the server with
> PORT=3000  ROOT_URL=http://localhost:3000   MONGO_URL=mongodb://<user>:<password>@<host>:<port>/dataurlfrommongolabs    $HOME/meteor/dev_bundle/bin/node main.js

(And yes, I am using a DB on our side and the DB is working fine)

**Error:**
> /home/pi/rocketchat/bundle/programs/server/node_modules/fibers/future.js:278
> 						throw(ex);
> 						      ^
> [object Object]
>     at Object.Future.wait (/home/pi/rocketchat/bundle/programs/server/node_modules/fibers/future.js:398:15)
>     at new MongoConnection (packages/mongo/mongo_driver.js:213:1)
>     at new MongoInternals.RemoteCollectionDriver (packages/mongo/remote_collection_driver.js:4:1)
>     at Object.<anonymous> (packages/mongo/remote_collection_driver.js:38:1)
>     at Object.defaultRemoteCollectionDriver (packages/underscore/underscore.js:750:1)
>     at new Mongo.Collection (packages/mongo/collection.js:102:1)
>     at AccountsServer.AccountsCommon (accounts_common.js:23:18)
>     at new AccountsServer (accounts_server.js:16:5)
>     at Package (globals_server.js:5:12)
>     at /home/pi/rocketchat/bundle/programs/server/packages/accounts-base.js:1762:4

What can I do here? I am already trying to get Rocket.Chat running the whole week.
Used Pi 3b+ before, now trying it iwht Pi 3b.
Clean and fresh Raspbian installation, tried every method. Even with ubuntu core and so on, everything really "sad" and not working.

Thanks for any help :)

**Comment by Akomd** [comment]
Hello :)
First, let me apologize for my poor English :(
I hope this will help you.

I found the way to working RocketChat 0.39.0 in Pi 3b. 
It is by installing Ubuntu Core 16 on Raspberry Pi, then installing Docker on it. Docker is installed by snap.
Then starting two application,  MongoDB server and Rocket Chat server,  on Docker.

I used "mangoraft/mongodb-arm" Docker Image, it is MongoDB version 2.6 server on Docker.
And I used "resin/rpi-raspbian:jessie" Docker Image, it is Raspbian Jessie base Image for installing Rocket Chat on Docker.
Install RocketChat on the Docker Container of "resin/rpi-raspbian:jessie", used the manual installation guide https://github.com/RocketChat/Rocket.Chat.RaspberryPi .

**Comment by eszeus** [comment]
@Akomd Hello there, I am not familiar with Docker, so I dont know how you managed that part :D 
Could you explain that a little bit further?
I installed docker on ubuntu core now.

**Comment by Akomd** [comment]
@eszeus Hello :)
Details are written, soon. First, translate this site into English and read it. Please wait :(

**Comment by Sing-Li** [comment]
The 1.0.x official snap release of Rocket.Chat no longer has such problems.
