### ISSUE TITLE
https://cdn-download.rocket.chat/build/rocket.chat-pi-develop.tgz not reachable/ OFFLINE?

### ISSUE THREAD

**Issue by eszeus** [RocketChat/Rocket.Chat.RaspberryPi#33]
Hello there,

the Rocketchat Download-link for the Pi seems to be offline/not reachable.
https://cdn-download.rocket.chat/build/rocket.chat-pi-develop.tgz

Anyone else having this probleme?

**Comment by tassoevan** [comment]
@shweshipu https://forums.rocket.chat/t/armhf-snap-builds-for-raspberry-pi/841/19
@geekgonecrazy Should we update the README?

**Comment by geekgonecrazy** [comment]
We should for sure remove the link.  If someone wants to build they will have to do them selves pretty much :(  Or use snaps

**Comment by Sing-Li** [comment]
Please follow the README and use snap based install with the latest Raspbian Buster Lite release.
