### ISSUE TITLE
Rocket.Chat on Qnap TS-431X with ARM architektur

### ISSUE THREAD

**Issue by gamegear04** [RocketChat/Rocket.Chat.RaspberryPi#38]
Hello,
I have a Docker container with arm32v7 / ubuntu: xenial installed on my Qnap TS-431X. Is it possible to install Rocket.chat on it and if so how?

With snap, it can not be installed in any case. = (

Could someone please help me there? Or. create a container that works?

Ever thank you in advance!

Best regards

**Comment by Sing-Li** [comment]
It might be possible.  Try instructions here:

https://github.com/RocketChat/Rocket.Chat.Embedded.armhf/tree/develop/docker

But to run RC and docker, you really should have at least 2GB or RAM or more.
