### ISSUE TITLE
Problem installing Rocket Chat.

### ISSUE THREAD

**Issue by SadWorm** [RocketChat/Rocket.Chat.RaspberryPi#39]
I've tried to install Rocket Chat on my raspberry pi following this guide: [(https://github.com/RocketChat/Rocket.Chat.RaspberryPi)]

After applying "sudo snap install rocket chat-server" reported a mistake, I didn't remember.

> localhost:3000 doesn't work
> curl -i localhost:3000 gives "curl: (7) Failed to connect to localhost port 3000: Connection refused"

When I'm trying to apply `sudo snap install rocket chat-server` one more time "Illegal instruction" appears. When trying to delete the package tells that no such package installed.

Looks like snap is down, haven't find a way to repair it yet.

Help ,me please. Really like the idea of using rocket chat on my local.

Best regards, Alexey.

**Comment by SadWorm** [comment]
Have found a way to repair snap:
```
sudo apt autoremove --purge snapd
rm -fr ~/snap
```
Started the installation process of Rocket Chat again. And here is the mistake:

> error: cannot communicate with server: Get http://localhost/v2/changes/1: dial unix /run/snapd.socket: connect: connection refused

**Comment by SadWorm** [comment]
[log.txt](https://github.com/RocketChat/Rocket.Chat.RaspberryPi/files/3025356/log.txt)

**Comment by Sing-Li** [comment]
Please follow the latest README for working instructions.

Using Raspbian Buster Lite (July 2019 or later) with the latest snap install for 1.0.x official Rocket.Chat release will provide the smoothest installation experience to date.
