### ISSUE TITLE
snap install yields cannot open shared object file

### ISSUE THREAD

**Issue by jonnytest1** [RocketChat/Rocket.Chat.RaspberryPi#40]
Im getting this error just following the steps in the readme

```
error: cannot perform the following tasks:
- Run configure hook of "rocketchat-server" snap if present (run hook "configure":
-----
ERROR: ld.so: object '/usr/lib/arm-linux-gnueabihf/libarmmem.so' from /etc/ld.so.preload cannot be preloaded (cannot open shared object file): ignored.
"((enable)|(disable))" is not a valid, set to enable or disable
-----)

```

`uname -a`
Linux raspberrypi 4.14.79-v7+ #1159 SMP Sun Nov 4 17:50:20 GMT 2018 armv7l GNU/Linux

`cat /etc/os-release`
...
VERSION_ID="9"
VERSION="9 (stretch)"
ID=raspbian
ID_LIKE=debian
...

**Comment by nathanRamaNoodles** [comment]
Looks like a problem with the Raspberry Pi's snap core...It isn't there 😄.
So just install it and then refresh it:
```
sudo snap install core
sudo snap refresh core --beta
sudo reboot
```
Finally, install rocketchat server:
```
sudo snap install rocketchat-server
```
The server will be located at `http://<ipaddress>:3000`

It should work now.
