### ISSUE TITLE
Is it possible for me to chat with several Pis in my local area?

### ISSUE THREAD

**Issue by ben19871987** [RocketChat/Rocket.Chat.RaspberryPi#6]
Dear
Hi I have some questions. I appreciate if you can answer me.
Is it possible for me to chat with several Pis in my local area with access point and without connection to internet?
Chat interface is available on raspberry pi?
Yours

**Comment by Sing-Li** [comment]
100%  -  the function of Rocket.Chat on RaspberryPi is NOT dependent on the Internet.  

You can:
 * run and operate the chat server for users on your own LAN or private network
 * setup ad-hoc server in disaster zone, or other areas with no cellphone or Internet infrastructures

**Comment by ben19871987** [comment]
Dear 
Thank you for your answer. But what is “ad-hoc server in disaster zone”?

Is it such routing protocols for example B.A.T.M.A.N?
Are there video chat and voice chat interface available on raspberry? I mean something like GUI.

Yours

**Comment by Sing-Li** [comment]
Rocket.Chat runs as a server on the Pi 

You will need mobile phones, tablets, Chromebooks, or other devices to use it as clients.
