### ISSUE TITLE
Update Rocket.Chat.RaspberryPi to latest release?

### ISSUE THREAD

**Issue by PieterBogema** [RocketChat/Rocket.Chat.RaspberryPi#8]
Is there any way to update the 0.13.0 to the latest version of Rocket Chat?

**Comment by Sing-Li** [comment]
You can build it yourself on an ARM machine.  But it will involve installing  (flakey) ARM based meteor - then just follow 'standard meteor build' procedures and cross your fingers.

We're looking for someone with time on an ARM server / VPS to get builds automated. 

Closing issue.
